---
- include_tasks: setup-Debian.yml
  when: ansible_os_family == "Debian"

- name: Install Docker Engine.
  apt: 
    name: "{{ item }}"
    state: present

  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Install Docker Compose.
  get_url:
    url: "{{ docker_compose_repo_url }}"
    dest: "{{ docker_compose_dest_path }}"
    mode: "0755"

- name: Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: started
    enabled: yes
  notify: restart docker

- name: Flush handlers.
  meta: flush_handlers

- include_tasks: docker-users.yml
