---
- name: Ensure Docker's older versions are uninstalled.
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes

  loop: "{{ docker_old_versions }}"

- name: Ensure all prerequisites are installed.
  apt:
    name: "{{ item }}"
    state: present

  loop: "{{ docker_prerequisites }}"

- name: Add Docker GPG key.
  apt_key:
    url: "{{ docker_apt_repo_url }}/gpg"
    keyring: "/usr/share/keyrings/docker-archive-keyring.gpg"
    state: present

- name: Add Docker repository.
  apt_repository:
    filename: docker
    repo: "{{ docker_apt_repository }}"
    state: present
  notify: update cache

- name: Flush handlers.
  meta: flush_handlers
