---
- name: Ensure Docker older versions are uninstalled.
  apt:
    name: "{{ item }}"
    state: absent
    update_cache: yes

  loop:
   - docker
   - docker-engine
   - docker.io
   - containerd.io
   - runc

- name: Ensure all dependencies are installed.
  apt:
    name: "{{ item }}"
    state: present

  loop:
    - apt-transport-https
    - ca-certificates
    - gnupg

- name: Add Docker GPG key.
  apt_key:
    url: "{{ docker_repo_url }}/gpg"
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    state: present

- name: Add Docker repository.
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: yes
    